# Robot shape
footprint: [[0.30, 0.20], [0.30, -0.20], [-0.30, -0.20], [-0.30, 0.20]]
footprint_padding: 0.02

# Sensor (from your pointcloud_to_laserscan)
obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    sensor_frame: base_link
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    obstacle_range: 3.5
    raytrace_range: 4.0
    min_obstacle_height: -0.10
    max_obstacle_height: 0.50

