local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  transform_tolerance: 0.5

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # tight halo so you can pass gaps
  inflation_layer:
    inflation_radius: 0.15        # <= clearance âˆ’ 0.05 m
    cost_scaling_factor: 10.0     # very steep decay (short shadow)

