TrajectoryPlannerROS:
  holonomic_robot: false

  max_vel_x: 0.35
  min_vel_x: 0.08
  max_rot_vel: 0.8
  min_in_place_rotational_vel: 0.35
  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 8
  vtheta_samples: 20

  path_distance_bias: 10.0
  goal_distance_bias: 15.0
  occdist_scale: 0.6

  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: true

  meter_scoring: true

